#!/usr/bin/env python3
import sys
from teca import *

if len(sys.argv) != 2:
    sys.stderr.write('usage:\nnumber_of_tc_tracks [track file]\n\n')
    sys.exit(-1)

fn = sys.argv[1]

r = teca_table_reader.New()
r.set_file_name(fn)

dc = teca_dataset_capture.New()
dc.set_input_connection(r.get_output_port())
dc.update()

tab = as_teca_table(dc.get_dataset())

track_ids = set(tab.get_column('track_id').as_array())

sys.stderr.write('%d\n'%(len(track_ids)))
